[project]
name = "endoutbreakvbd"
requires-python = ">=3.11"
version = "0.0.0"

[tool.pixi.workspace]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]

[tool.pixi.dependencies]
annotated-types = "*"
arviz = "*"
climepi = "*"
matplotlib = "*"
numpy = "*"
pymc = "*"
scipy = "*"
statsmodels = "*"
tqdm = "*"
xarray = "*"

[tool.pixi.pypi-dependencies]
endoutbreakvbd = { path = ".", editable = true }
meteostat = "*"

[tool.pixi.feature.dev.dependencies]
ruff = "*"
ipykernel = "*"
jupyter_bokeh = "*"
snakemake = "*"

# [tool.pixi.feature.dev.pypi-dependencies]
# snakemake-executor-plugin-slurm = "*" # use pypi version because of https://github.com/snakemake/snakemake-executor-plugin-slurm/issues/356

[tool.pixi.environments]
default = { features = ["dev"], solve-group = "prod" }

[tool.pixi.feature.dev.tasks]
lint = "ruff check"
format = "ruff format"
